Sprint 7 solution in file manager
zlov82/java-kanban pull request #4
Opened 2024-05-05 18:44 UTC by zlov82

2024-05-06 19:20 UTC, YazykovMikhail requested changes

2024-05-06 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +    private final String pathToFileDb;
Поля обьявляются первыми в классе
Храни сам обект File
private final File file;

2024-05-06 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +        int ret = super.addNewTask(task);
не понятно что такое ret
id - понятно сразу)

2024-05-06 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +    private static void fromString(String fileLine, FileBackedTaskManager manager) {
Метод назыввется fromString - он должен что то возвращат ьиз строки, в данном случае задачу: 

```
public static Task taskFromString(String value) {
		final String[] values = value.split(",");
		final int id = Integer.parseInt(values[0]);
		final TaskType type = TaskType.valueOf(values[1]);
		final String name = values[2];
		final TaskStatus status = TaskStatus.valueOf(values[3]);
		final String description = values[4];
		if (type == TaskType.TASK) {
			return new Task(id, name, description, status);
		}
		if (type == TaskType.SUBTASK) {
			final int epicId = Integer.parseInt(values[5]);
			return new Subtask(id, name, description, status, epicId);
		}

		return new Epic(id, name, description, status);
	}
```

А добавлять их в хранилище - это дело метода который вызывает текущей, каждый должен отвечать за свое

2024-05-06 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/tasks/Task.java
Добавь поле TaskType taskType
или еще проще сделай метод для каждой задачи 
public TaskType getType() {
		return TaskType.TASK;
	}
который будет возвращать свой тип.

2024-05-06 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/tasks/Task.java
>      public String toString() {
Не стоит использовать базовый метод toString() в бизнес процессах, этот метод много где используется самой Джавой, для бизнес процесса стоит сделать отдельный метод который будет делать по конкретному шаблону, который отвечает бизнес треованиям

2024-05-06 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +
Стоит сделать отдельный метод toString который используется для бизнес процесов, например вот простой:
```
	public static String toString(Task task) {
		return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," + task.getDescription() + "," + (task.getType().equals(TaskType.SUBTASK) ? task.getEpicId() : "");
	}
```

2024-05-06 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +    private void save() {
Есть пару моментов которые можно улучшить:
1) Использовать буферизацию - экономит ресурсы
2) Не стоит использовать "\n" - в разных операционных системах перенос строки разный. Используй системный перенос строки

СПОЙЛЕР:
```
protected void save() {
		try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
			writer.write(CSVTaskFormat.getHeader());
			writer.newLine();

			for (Map.Entry<Integer, Task> entry : tasks.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			for (Map.Entry<Integer, Subtask> entry : subtasks.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			for (Map.Entry<Integer, Epic> entry : epics.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			writer.newLine();
		} catch (IOException e) {
			throw new ManagerSaveException("Can't save to file: " + file.getName(), e);
		}
	}
```

2024-05-06 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +    public static FileBackedTaskManager loadFromFile(File file) throws ManagerSaveException {
В целом ок, но есть что улучшить
1) можно не описывать в сигнатуре метода throws ManagerSaveException - это исключение от RuntimeException если оно произошло то по нашей логике что то сломало, специально говорить о том что его нужно обработать не нужно
2) Не востанавливается счетчик идентификатора
3) Можно не переделывать старые методы add что бы в зависимоси от наличия id они уменли добавлять - это может создать баги, когда с фронта будут приходить новые задачи уже с дентификатором. Добавляй прям сразу их в хранилище напрямую
4) Метод fromString должен создавать задачи из текста, а он к тому же еще и добавляет, каждый мтод должен отвечать за свою часть работы

СПОЙЛЕР:

```
public static FileBackedTaskManager loadFromFile(File file) {
		final FileBackedTaskManager taskManager = new FileBackedTaskManager(file);
		try {
			final String csv = Files.readString(file.toPath());
			final String[] lines = csv.split(System.lineSeparator());
			int generatorId = 0;
			for (int i = 1; i < lines.length; i++) {
				String line = lines[i];
				if (line.isEmpty()) {
					break;
				}
				final Task task = CSVTaskFormat.taskFromString(line);
				final int id = task.getId();
				if (id > generatorId) {
					generatorId = id;
				}
				taskManager.addAnyTask(task);
			}
			for (Map.Entry<Integer, Subtask> e : taskManager.subtasks.entrySet()) {
				final Subtask subtask = e.getValue();
				final Epic epic = taskManager.epics.get(subtask.getEpicId());
				epic.addSubtaskId(subtask.getId());
			}
			taskManager.uniqueId = generatorId;
		} catch (IOException e) {
			throw new ManagerSaveException("Can't read form file: " + file.getName(), e);
		}
		return taskManager;
	}

```

доп метод:
```
protected void addAnyTask(Task task) {
		final int id = task.getId();
		switch (task.getType()) {
			case TASK:
				tasks.put(id, task);
				break;
			case SUBTASK:
				subtasks.put(id, (Subtask) task);
				break;
			case EPIC:
				epics.put(id, (Epic) task);
				break;
		}
	}
```

2024-05-06 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +    @Override
Все методы переопреелять не нужно, только те которые влияют на состояние задач. 
Раз тут состояние не меняется, то и сохранять не нужено и соответсвенно переопределять, ведь он в итоге делает тоже самое
Стоит убрать все методы не меняющие состояние

2024-05-06 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/Managers.java
> +        return new FileBackedTaskManager(new File("res.csv"));
Положи файл в папку
"resources/task.csv"

2024-05-06 21:03 UTC, zlov82 commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +    public static FileBackedTaskManager loadFromFile(File file) throws ManagerSaveException {
Счетчик идентификатора у меня восстанавливался в private static void fromString
       int taskId = Integer.parseInt(lines[0]);
        if (manager.uniqueId < taskId) {
            manager.uniqueId = taskId;
        }

2024-05-06 22:07 UTC, zlov82 commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +
task.getEpicId() - метод не находиться в таком виде, несмотря на то, что он публичный

2024-05-07 07:42 UTC, YazykovMikhail approved these changes

2024-05-07 07:42 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +            throw new ManagerSaveException(e);
стоит добавлять какое то описание к исключение, например как было в предыдущем ревью

2024-05-07 07:42 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +            throw new ManagerSaveException(e);
На будущее

2024-05-07 07:42 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/FileBackedTaskManager.java
> +            throw new ManagerSaveException(e);
Стоит добавлять текст в исключениях, с опсианием/причиной

2024-05-07 08:13 UTC, merged