Sprint 8 solution time and duration
zlov82/java-kanban pull request #6
Opened 2024-05-14 08:36 UTC by zlov82

2024-05-14 18:11 UTC, YazykovMikhail requested changes

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +        sortedTasks = new TreeSet<>(comparator);
prioritizedTasks = new TreeSet<>(Comparator.comparing(Task::getStartTime));

вот так будет получше

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +    protected final Set<Task> sortedTasks;
назови лучше
prioritizedTasks
лучше называть не что делали с переменными, а почему

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +        ;
Похоже это лишнее

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +        if (crossTask.isPresent()) return true;
{} - обязательны

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +        if (task.getStartTime() != null) {
эта проверка не нужна: в методе 
isCrossedTimeTask
она уже есть

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +        if (task.getStartTime() != null) {
ПОправь везде

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +        ;
Поправь везде

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
>          updateEpicStatus(subtask.getEpicId());
Что бы не писать везде по две строки:
```
        updateEpicStatus(subtask.getEpicId());
        updateEpicDataAndDuration(subtask.getEpicId());
```
стоит обьеденить их в один метод, ниже покажу пример

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
Стоит обьеденить методы обновдения эпика, что бы везде не дублирвоать две строки, а потом еще в кадом методе получать из хранилища сам эпик:

```
    private void updateEpic(int id) {
        Epic epic = epicsDb.get(id);
        updateEpicDataAndDuration(epic);
        updateEpicStatus(epic)
    }
```

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/tasks/Subtask.java
> +    private Duration duration;
private Duration duration;
    private LocalDateTime startTime;
Эти поля уже есть тут, они унаследованы от Task

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/tasks/Subtask.java
> +                ", startTime='" + startTime + '\'' +
Если нужны тут, то вызывать методы  getDuration()
или еще лучше обьяви protected в Task что бы у наследников был прямой доступ

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/tasks/Epic.java
> +    private Duration duration;
private Duration duration;
private LocalDateTime startTime;
Эти поля уже есть тут, они унаследованы от Task

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/tasks/Epic.java
> +
У эпик должно быть поле 
	private LocalDateTime endTime;
которое высчитывается методом updateEpicDataAndDuration и завиист от его сабтасок

2024-05-14 18:11 UTC, YazykovMikhail commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +    protected void updateEpicDataAndDuration(int epicId) {
Используй методы вычисления окончания задач, которые у тебя есть в Subtask
	private void updateEpicDuration(Epic epic) {
		List<Integer> subs = epic.getSubtaskIds();
		if (subs.isEmpty()) {
			epic.setDuration(0L);
			return;
		}
		LocalDateTime start = LocalDateTime.MAX;
		LocalDateTime end = LocalDateTime.MIN;
		long duration = 0L;
		for (int id : subs) {
			final Subtask subtask = subtasks.get(id);
			final LocalDateTime startTime = subtask.getStartTime();
			final LocalDateTime endTime = subtask.getEndTime();
			if (startTime.isBefore(start)) {
				start = startTime;
			}
			if (endTime.isAfter(end)) {
				end = endTime;
			}
			duration += subtask.getDuration();
		}
		epic.setDuration(duration);
		epic.setStartTime(start);
		epic.setEndTime(end);
	}

2024-05-16 21:54 UTC, zlov82 commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +    protected void updateEpicDataAndDuration(int epicId) {
Михаил, не понимаю зачем мне делать отдельную функцию по вычислению времени эпика, когда у меня по факту то же самое делается в методе updateEpicDataAndDuration:
 - точно так же пробегается по всем подзадачам эпика, и есть есть у подзадачи есть время исполнения - делаем инкремент на него.
 
В тестах эпика есть тест void shouldCorrectDateAndDurationInEpic() который как раз проверяет вычисляет корректную дату старта эпика и его продолжительности

2024-05-16 21:57 UTC, zlov82 commented on src/ru/yandex/javacourse/kanban/tasks/Epic.java
> +
Михаил, скажите мне логику этого поля?
Если я правильно понимаю, то у эпика есть наследованное поле duration, 
в методе updateEpicDataAndDuration как раз и вычисляется duration эпика = сумме duration подзадач эпика.
и пересчитывать duration и startTime эпика мы спокойно можем при добавлении/обновлении подзадач

2024-05-16 22:07 UTC, zlov82 commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +    protected void updateEpicDataAndDuration(int epicId) {
Перечитал ТЗ, понял.

2024-05-16 22:07 UTC, zlov82 commented on src/ru/yandex/javacourse/kanban/tasks/Epic.java
> +
Перечитал ТЗ - понял

2024-05-16 22:40 UTC, zlov82 commented on src/ru/yandex/javacourse/kanban/manager/InMemoryTaskManager.java
> +        if (task.getStartTime() != null) {
В isCrossedTimeTask я проверяю задачу на пересечение по времени в приоретизированном списке задач.
Но по ТЗ в приоретизированный список не должно попадать задач без времени старта. Именно поэтому перед добавлением в приоретизированный список у меня стоит проверка, что начальная дата не пустая.

2024-05-17 05:35 UTC, YazykovMikhail approved these changes

2024-05-17 08:55 UTC, merged